// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlProjectsPowerTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "SqlProjectsPowerTools.0e226f35-6d47-4156-88df-f9d40db5e2d1";
        public const string Name = "SQL Database Projects Power Tools";
        public const string Description = @"SQL Database Projects Power Tools";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "Erik Ejlskov Jensen (Delegate)";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
