// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlProjectsPowerTools
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsixString = "df7cd9f5-a5c6-4564-ae14-233965c617fb";
        public static Guid Vsix = new Guid(VsixString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int cmdidSqlMenuAbout = 0x0300;
        public const int cmdidSqlBuild = 0x0400;
        public const int cmdidSqlMenu = 0x0500;
        public const int cmdidSqlMenuGroup = 0x0600;
        public const int cmdidSqlProjectMenuItemsGroup = 0x0700;
        public const int cmdidSqlAboutMenuItemsGroup = 0x0800;
        public const int cmdidSqlProjectMenu = 0x0003;
        public const int cmdidSqlProjectMenuGroup = 0x0004;
        public const int cmdidAnalyze = 0x0001;
        public const int cmdidImport = 0x0002;
        public const int cmdidCompare = 0x0005;
        public const int cmdidErDiagram = 0x0007;
        public const int cmdidReverseEngineerDab = 0x0012;
        public const int cmdidAbout = 0x0006;
        public const int cmdidOptions = 0x0010;
        public const int cmdidUnpack = 0x0008;
    }
}
