// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SqlProjectsPowerTools
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VsixString = "9afa5961-b489-4faf-9714-294260affdf5";
        public static Guid Vsix = new Guid(VsixString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int cmdidSqlMenu = 0x0500;
        public const int cmdidSqlMenuGroup = 0x0600;
        public const int cmdidSqlProjectMenuItemsGroup = 0x0700;
        public const int cmdidImportDatabase = 0x0010;
    }
}
